### ISSUE TITLE
Please make a new release 1.0.2

### ISSUE THREAD

**Issue by tseemann** [rega-cev/virulign#10]
I found some bugs in 1.0.1 and then realised you had already fixed them in master.
Can you please make a new release 1.0.2 or at least a tag?
I am packaging for brew and conda.

```
git tag v1.0.2
git push --tags
```

Thank you!

**Comment by plibin** [comment]
I created a new tag and pushed it.

**Comment by tseemann** [comment]
Thanks @plibin
