### ISSUE TITLE
Now in brew

### ISSUE THREAD

**Issue by tseemann** [rega-cev/virulign#11]
https://github.com/brewsci/homebrew-bio/pull/731

```
brew install brewsci/bio/virulign
```

I had to hack it to install correctly until #10 is done

**Comment by plibin** [comment]
OK, should be fine now.

Thanks for your efforts!
I will add the brew installation mode to the github start page.

**Comment by plibin** [comment]
I still receive an error when trying to install virulign with brew:
(base) _~/projects/virulign>brew install brewsci/bio/virulign
Error: No available formula with the name "brewsci/bio/virulign" 
==> Searching for a previously deleted formula (in the last month)...
Warning: brewsci/bio is shallow clone. To get complete history run:
  git -C "$(brew --repo brewsci/bio)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
(base) _~/projects/virulign>brew install brewsci/bio/virulign
Error: No available formula with the name "brewsci/bio/virulign" 
==> Searching for a previously deleted formula (in the last month)...
Warning: brewsci/bio is shallow clone. To get complete history run:
  git -C "$(brew --repo brewsci/bio)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

**Comment by tseemann** [comment]
@plibin 
```
brew search virulign
==> Formulae
brewsci/bio/virulign
```

Maybe you need to update your brew?
What does `brew update` say?
And `brew doctor` ?

Maybe try `brew tap brewsci/bio && brew install virulign` instead.

P.S. it looks like you are mixing `conda` with `brew`. That is a bad idea!
