### ISSUE TITLE
Add a "time to complete" message to the screen output.

### ISSUE THREAD

**Issue by plibin** [rega-cev/virulign#3]

**Comment by plibin** [comment]
I propose to update the software such that it reports:
- the percentage of aligned sequences
- the estimated time left to compute the pending alignments
  
However, VIRULIGN is used in different contexts, including in scripts where a minimum of output to the command line is preferred. For this reason, we allow this new feature to be enabled using the flag '--progress yes'.

**Comment by ktheyss** [comment]
This works well on Mac and Windows.
