### ISSUE TITLE
virulign installation problems

### ISSUE THREAD

**Issue by thierryjanssens** [rega-cev/virulign#5]
Hello,

I am attempting to install the virulign package in two ways. We use a strict conda environment setting on our analysis server, s ideally all dependencies should be included somehow.

First attempt: via the binary archive 
$tar -xzvf virulign-linux-64bit.tgz
$./virulign
$./virulign: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./virulign)
$./virulign: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./virulign)
$./virulign: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./virulign)
$./virulign: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./virulign)

The second attempt was cloning the git and building from source, according to BUILD.txt.
(conda_env) [user@hostname build]$ make install
[ 35%] Built target mxml
[ 41%] Built target mxml-utils
[ 61%] Built target virulignlib
[ 93%] Built target seq
[100%] Built target virulign
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/CodonAlign.h
CMake Error at src/libseq/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/data/anaconda3/envs/conda_env/virulign/src/libseq/CodonAlign.h" to
  "/usr/local/include/CodonAlign.h".
Call Stack (most recent call first):
  src/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)

make: *** [Makefile:86: install] Error 1

We have no writing permission to usr/local and changing this path  in a "hard-coded" way it in earlier make_install files is not working.

I am looking forward for your answer.

Regards,

Thierry

**Comment by thierryjanssens** [comment]
Hi,

I have succeed to perform cmake to a desired folder by making use of the -DCMAKE_BUILD_TYPE=Release variable.
I get an include folder with a bunch of files. How can virulign be executed?

Kind regards,

Thierry

**Comment by plibin** [comment]
Dear Thierry,

first of all, I'm sorry you ran into this problem. Also, I greatly appreciate that you took the time to report the issue, so we can try to improve our software and documentation.

For your first comment, I think you might solve the problem by using cmake's CMAKE_INSTALL_PREFIX option, this option allows you to configure where the installation should be carried out. Excuse me if you did use this option and I misunderstood. After looking at VIRULIGN's BUILD.txt I realised this option could be advertised and explained in a clearer way, so I will work on improving this documentation.

For your second comment, you can find a virulign binary in the build/src directory, after running cmake and make. But installing it the way I suggest in the previous comment might already solve your problem?

Finally, our team is very much interested in finding more convenient ways to distribute our software, and conda seems to have quite some benefits. We'll definitely have a look into it.

Kind regards,

Pieter

**Comment by thierryjanssens** [comment]
Dear Pieter,

thank you for your swift reply. 
As mentioned in my second post I have used the CMAKE_INSTALL_PREFIX  variable in a later attempt.
I found the executable in the  build/src/ folder.
Thank you for your precious time.

Kind regards,

Thierry

**Comment by plibin** [comment]
Dear Thierry, 

I went through our installation CMake scripts, and the virulign binary is indeed not installed. Thanks for reporting this issue, I fixed it, and pushed the fix to the git master branch.

I also updated the documentation to improve the build instructions.

Please let me know if this solves your problem, if so, I will close this issue.

Thanks and kind regards,

Pieter

**Comment by thierryjanssens** [comment]
Hi Pieter,

thanks for helping us out.
The issue is solved now.

Regards,

Thierry
